# -*- coding: utf-8 -*-
# ───────────────────────────────────────────────────────────────
# File: harpia_benchmark_reporter_en.py (CORRECTED VERSION)
# Purpose: Reads a CSV generated by the HARPIA/SPHY simulation, calculates 
#          metrics, and generates the stability graph.
# Author: Gemini (With correction applied)
# ───────────────────────────────────────────────────────────────

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import sys
from scipy.interpolate import interp1d
from datetime import datetime
import time

# ----------------------------------------------------------------------
# Configurations
# ----------------------------------------------------------------------
LOG_DIR = "reports_harpia_analysis"
os.makedirs(LOG_DIR, exist_ok=True)
SPHY_SUCCESS_THRESHOLD = 90.0
# Defines the base Initial Coherence as 90.0, according to the original simulator setup.
INITIAL_COHERENCE_BASE = 90.0 

# ----------------------------------------------------------------------
# 1. MAIN FUNCTIONS
# ----------------------------------------------------------------------

def calculate_metrics(df, total_sim_time):
    """Calculates all performance and stability metrics."""
    total_frames = len(df)
    
    # Coherence and Acceptance Metrics
    valid_states = df[df['Accepted'] == '✅'].shape[0]
    acceptance_rate = 100 * (valid_states / total_frames) if total_frames > 0 else 0
    
    # SPHY Stability Metrics
    sphy_evolution = df['SPHY (%)'].values
    mean_stability = np.mean(sphy_evolution)
    stability_variance = np.var(sphy_evolution)
    
    # Gains
    # ❗ CORRECTION APPLIED HERE: Uses the base value 90.0 as Initial Coherence
    initial_coherence = INITIAL_COHERENCE_BASE 
    final_coherence = df['SPHY (%)'].iloc[-1] if total_frames > 0 else 0.0
    coherence_gain = final_coherence - initial_coherence
    
    # Meissner Boost
    boost_count = df[df['Boost'] > 0].shape[0]
    meissner_boost_success_rate = 100 * (boost_count / total_frames) if total_frames > 0 else 0

    return {
        "total_frames": total_frames,
        "valid_states": valid_states,
        "acceptance_rate": acceptance_rate,
        "mean_stability": mean_stability,
        "stability_variance": stability_variance,
        "coherence_gain": coherence_gain,
        "meissner_boost_rate": meissner_boost_success_rate,
        "total_time": total_sim_time,
        "sphy_evolution": sphy_evolution
    }

def generate_report(metrics):
    """Prints the benchmark report to the console."""
    
    total_time_minutes = metrics["total_time"] / 60
    
    if metrics["total_time"] > 0.001: 
        fps = metrics["total_frames"] / metrics["total_time"]
    else:
        # Avoid division by zero if time is effectively 0
        fps = metrics["total_frames"] / 0.01 

    print("\n" + "=" * 60)
    print("         HARPIA BENCHMARK REPORT (CSV ANALYSIS) 🧾")
    print("=" * 60)
    print(f"⏱ Total Frames Analyzed: {metrics['total_frames']:,}")
    print(f"⏱ Estimated FPS/it/s: {fps:.2f}")
    print(f"⏱ Total Sim Time (Estimated): {metrics['total_time']:.2f}s ({total_time_minutes:.2f} min)")
    
    print("\n--- Performance and Acceptance ---")
    print(f"✅ States Accepted: {metrics['valid_states']}/{metrics['total_frames']} | {metrics['acceptance_rate']:.2f}%")
    print(f"📈 Meissner Boost Rate: {metrics['meissner_boost_rate']:.2f}% (Meissner Correction Applied)")
    
    print("\n--- Coherence and Stability ---")
    print(f"📊 Mean Stability Index: {metrics['mean_stability']:.4f}%")
    print(f"📊 Stability Standard Deviation: {np.sqrt(metrics['stability_variance']):.4f}") 
    print(f"🚀 Total Coherence Gain: {metrics['coherence_gain']:.4f}%")
    print("=" * 60)


def plot_analysis_graph(sphy_evolution, filename_prefix):
    """Recreates the SPHY stability graph."""
    
    sphy_evolution = np.array(sphy_evolution)
    if sphy_evolution.size == 0:
        print("❌ No data to plot.")
        return

    tempo = np.linspace(0, 1, len(sphy_evolution))
    
    # Create cubic interpolation signals (similar to the original simulation)
    sinais = [interp1d(tempo, np.roll(sphy_evolution, i), kind='cubic') for i in range(2)] 
    novo_tempo = np.linspace(0, 1, 2000)
    
    dados = [sinal(novo_tempo) + np.random.normal(0, 0.15, len(novo_tempo)) for sinal in sinais]
    pesos = np.linspace(1, 1.5, 2)
    entanglement = np.average(dados, axis=0, weights=pesos) 

    mean_stability = np.mean(entanglement)
    stability_variance = np.var(entanglement)
    
    # --- GRAPH GENERATION --- 
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 12)) 
    
    # GRAPH 1: Entanglement with Noise and Phase-Shifted Signals
    ax1.plot(novo_tempo, entanglement, 'k--', linewidth=2, label="SPHY Stabilized Coherence")
    for i in range(len(dados)):
        ax1.plot(novo_tempo, dados[i], alpha=0.3, color='blue' if i == 0 else 'red') 
    ax1.set_xlabel("Normalized Time")
    ax1.set_ylabel("SPHY Coherence/Amplitude (%)")
    ax1.set_title("GHZ CV Entanglement - Coherence and HARPIA Modulation")
    ax1.legend()
    ax1.grid()
    
    # GRAPH 2: Stability and Mean
    ax2.plot(novo_tempo, entanglement, 'k-', label="SPHY Stabilized Coherence")
    ax2.axhline(mean_stability, color='green', linestyle='--', label=f"Mean Coherence: {mean_stability:.2f}%")
    ax2.axhline(mean_stability + np.sqrt(stability_variance), color='orange', linestyle='--', label=f"± Std Dev: {np.sqrt(stability_variance):.4f}")
    ax2.axhline(mean_stability - np.sqrt(stability_variance), color='orange', linestyle='--')
    ax2.set_xlabel("Normalized Time")
    ax2.set_ylabel("SPHY Coherence/Amplitude (%)")
    ax2.set_title("Coherence Stability via HARPIA/Meissner - Mean and Standard Deviation")
    ax2.legend()
    ax2.grid()

    fig_filename = os.path.join(LOG_DIR, f"report_graph_{filename_prefix}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.png")
    fig.suptitle("HARPIA Quantum Benchmark Analysis: Coherence Stability", fontsize=16)
    fig.tight_layout(rect=[0, 0.03, 1, 0.95])
    
    plt.savefig(fig_filename, dpi=300)
    print(f"\n📊 Graph saved as: {fig_filename}")
    
    plt.show()

# ----------------------------------------------------------------------
# 2. EXECUTION FUNCTION
# ----------------------------------------------------------------------

def run_reporter():
    """Main function to request the CSV path and execute the analysis."""
    csv_path = input("➡️ Enter the full path of the HARPIA simulation CSV file: ")
    
    if not os.path.exists(csv_path):
        print(f"\n❌ Error: File not found in path: {csv_path}")
        sys.exit(1)

    total_sim_time = 0.0

    try:
        start_time_analysis = time.time()
        df = pd.read_csv(csv_path)
        end_time_analysis = time.time()

        # Tries to extract the simulation time
        try:
            df['Timestamp'] = pd.to_datetime(df['Timestamp'])
            
            time_start_sim = df['Timestamp'].iloc[0]
            time_end_sim = df['Timestamp'].iloc[-1]
            total_sim_time = (time_end_sim - time_start_sim).total_seconds()
            
            if total_sim_time <= 0:
                total_sim_time = end_time_analysis - start_time_analysis
                print("\n⚠️ Warning: Invalid Timestamps in CSV. Using analysis execution time for estimation.")

        except Exception:
            total_sim_time = end_time_analysis - start_time_analysis 
            print("\n⚠️ Warning: 'Timestamp' column not found or invalid format. Using analysis execution time for estimation.")
        
        # 1. Calculate Metrics
        metrics = calculate_metrics(df, total_sim_time)
        
        # 2. Generate Report
        generate_report(metrics)
        
        # 3. Generate Graph
        filename_prefix = os.path.basename(csv_path).replace('.csv', '')
        plot_analysis_graph(metrics['sphy_evolution'], filename_prefix)
        
    except Exception as e:
        print(f"\n❌ Critical error when processing or analyzing the CSV: {e}")
        print("Check if the CSV has the expected columns: 'SPHY (%)', 'Accepted', 'Boost', and 'Timestamp'.")
        sys.exit(1)

if __name__ == "__main__":
    run_reporter()